### ISSUE TITLE
Three-argument form of conman query functions?

### ISSUE THREAD

**Issue by genovese** [luminus-framework/conman#12]
The options that Yesql offers for specifying processors in its query functions are sometimes useful, and it would be nice if conman offered some support for that feature in those cases.

For instance, this could be done relatively clearly and at little cost with a 3-ary form of the query functions in `bind-connection`, something like

```
([args# conn# options#] (yesql-query# args# (merge {:connection conn#} options#)))
```

where `options#` is a map of processors. This could even replace the 2-ary form directly
with

```
([args# conn# & [options#]] (yesql-query# args# (merge {:connection conn#} options#)))
```

if that were desirable.

What do you think? 
Thanks.

**Comment by yogthos** [comment]
That seems reasonable to me, if you'd be up for a pr I can push out a new release with the update.

**Comment by genovese** [comment]
Will do, thanks.

**Comment by yogthos** [comment]
I don't think this will apply now that conman is using HugSQL.
