### ISSUE TITLE
driverType on Pool Configuration

### ISSUE THREAD

**Issue by alan-saar** [luminus-framework/conman#16]
The IBM® Data Server Driver for JDBC and SQLJ supports two types of connectivity: type 2 connectivity and type 4 connectivity.
Type 2 connectivity requires a DB2 client (or server) installation and has a restriction in that the "bitness" of the java application must match with the DB2 client ( or server) instance.
The Data Server Driver for Type 4 connection does not require the use of the native DB2 libraries. 
So Oracle:
[Oracle Pool API](http://docs.oracle.com/cd/E11882_01/appdev.112/e13995/oracle/jdbc/pool/OracleDataSource.html)

```
 void   setDriverType(java.lang.String dt)
          Set the JDBC driver type
```

It would be nice if:

```
(defn- make-config
  [{:keys [jdbc-url datasource datasource-classname username
           password auto-commit? conn-timeout idle-timeout
           max-lifetime min-idle max-pool-size pool-name]}]
  (let [cfg (HikariConfig.)
        uri (when jdbc-url (to-jdbc-uri jdbc-url))]
    (when uri                  (.setJdbcUrl cfg uri))
    (when datasource           (.setDataSource cfg datasource))
    (when datasource-classname (.setDataSourceClassName cfg datasource-classname))
    (when username             (.setUsername cfg username))
    (when password             (.setPassword cfg password))
    (when (some? auto-commit?) (.setAutoCommit cfg auto-commit?))
    (when conn-timeout         (.setConnectionTimeout cfg conn-timeout))
    (when idle-timeout         (.setIdleTimeout cfg conn-timeout))
    (when max-lifetime         (.setMaxLifetime cfg max-lifetime))
    (when max-pool-size        (.setMaximumPoolSize cfg max-pool-size))
    (when min-idle             (.setMinimumIdle cfg min-idle))
    (when pool-name            (.setPoolName cfg pool-name))
    cfg))
```

have a .setDriverType

**Comment by yogthos** [comment]
Hmm, it doesn't seem to be a `.setDriverType` in the [HikariConfig](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariConfig.java) class. If you can see something that would be equivalent I can definitely add that to the options.

**Comment by alan-saar** [comment]
It can be done setting the properties by reflection in Hikari. I'm passing the datasource object already set, which to me is also a valid solution. I'm closing this issue. 
PS: Your book is great, I read the beta. I am eagerly awaiting the publication!

**Comment by yogthos** [comment]
Perfect, and glad to hear it.
