### ISSUE TITLE
Error after update 0.4.1 -> 0.4.7

### ISSUE THREAD

**Issue by Ninerian** [luminus-framework/conman#18]
I updated conman in my dependencies to 0.4.7 and changed my code, according to your documentation. But when I now execute a database query, the following error is thrown:

`db-spec mount.core.DerefableState@3cb8256c is missing a required parameter  clojure.java.jdbc/get-connection (jdbc.clj:292)`

My connection code is the following:

``` clojure
(ns wamp-authenticator.db.core
  (:require
    [clojure.java.jdbc :as jdbc]
    [mount.core :refer [defstate]]
    [conman.core :as conman]
    [environ.core :refer [env]])
  (:import [java.sql
            BatchUpdateException
            PreparedStatement]))

(def pool-spec
  {:adapter    :mysql
   :init-size  1
   :min-idle   1
   :max-idle   4
   :max-active 32})

(defn connect! []
    (conman/connect!
        (assoc
            pool-spec
            :jdbc-url (env :database-url))))

(defn disconnect! [conn]
    (conman/disconnect! conn))

(defstate ^:dynamic *db*
          :start (connect!)
          :stop (disconnect! *db*))

(conman/bind-connection *db* "queries.sql")
```

I also looked into the code of the luminus template and in the documentation, but didn't find a clue. Maybe you could help me with this.

**Comment by yogthos** [comment]
The error indicates that the connection wasn't started. Mount will only start states that are used somewhere. So, once you reference the `wamp-authenticator.db.core` namespace in another namespace that will trigger the state to start.

You can start the database from the REPL by running:

``` clojure
(mount.core/start #'wamp-authenticator.config/env #'wamp-authenticator.db.core/*db*)
```

**Comment by Ninerian** [comment]
In the `wamp-authenticator.core`I reference the namespace with `[wamp-authenticator.db.core :as db]` .
Before the update I had a connect function which I called from the core. Do I have to use this again?

**Comment by yogthos** [comment]
Ah you have to run `mount.core/start` in order to load the components. The current template does that in the `core/start-app` function. Conversely, you should also run `(mount/stop)` in the `stop-app` function to cleanup the resources when shutting down.
