### ISSUE TITLE
:adapter bug?

### ISSUE THREAD

**Issue by dotemacs** [luminus-framework/conman#22]
Hello,

following the simple steps in the README for the setup and usage of `conman`, I get the following error:

`IllegalArgumentException Invalid configuration options: (:adapter) sun.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)`

when doing this:

``` clojure
(require 'myapp.db :verbose)
(in-ns 'myapp.db)
(mount/start)
```

The cause of this is the `:adapter` declaration, if you use the following (as per the README instructions):

``` clojure
(def pool-spec
  {:adapter    :postgresql
   :init-size  1
   :min-idle   1
   :max-idle   4
   :max-active 32
   :jdbc-url "jdbc:postgresql://localhost/myapp"})
```

If I comment out `:adapter` line, the problem disapears and I can sucessfully 

``` clojure
(mount/start)
{:started ["#'myapp.db/*db*"]}
```

In order to replicate this, I created a demo app with all the steps in the README [here](https://github.com/dotemacs/maybe-conman-bug), for which I create a database using

```
create database myapp;
```

Is this a bug, or am I doing something wrong here?

Thank you for your time in advance

**Comment by yogthos** [comment]
Yeah, the adapter is no longer a valid parameter since I switched conman to use the [hikari-cp](https://github.com/tomekw/hikari-cp) library. I just updated the readme to remove it from the example.

**Comment by dotemacs** [comment]
Thank you for that 👍 

Should this entry also be re-visited:

https://github.com/luminus-framework/conman/blame/master/README.md#L95

(linked it via the `blame` view, as there wasn't a way to do line-number mode when viewing the README.md) ?

**Comment by yogthos** [comment]
yeah definitely, thanks for being thorough :)

**Comment by dotemacs** [comment]
No, thank you for the library :)

Closing this issue as it's resolved

**Comment by yogthos** [comment]
👍
