### ISSUE TITLE
error about sql: manipulate data with executeQuery

### ISSUE THREAD

**Issue by g1eny0ung** [luminus-framework/conman#23]
Recently I read the book Web development with clojure, when I read the chapter 8 Picture Gallery, the task A:account registration, there is a function named **register!**.

When I finish the function and test it, it tell me the mount error *_mount.core.DerefableState is missing a required parameter *_, and I found it solution in the pragmatic book forum.

But I continue to execute it, it handle me a **java nullpointerexception**, I use the cider, so I debug it.

And it break in the **db/create-user!**, it tell me 
**Cannot issue data manipulation statements with executeQuery()**

I know a litte about java, I found this question in stackoverflow
[http://stackoverflow.com/questions/1905607/cannot-issue-data-manipulation-statements-with-executequery](http://stackoverflow.com/questions/1905607/cannot-issue-data-manipulation-statements-with-executequery)

it say the **executequery()** only in select query, so up to now, it seems that a error about sql query, and I can't found it solution,does the hugsql package this method?And how can I fix this problem?

here is my code:

``` clojure
(defn register! [{:keys [session]} user]
  (if (registration-errors user)
    (response/precondition-failed {:result :error})
    (try
      (db/create-user!
       (-> user
           (dissoc :pass-confirm)
           (update :pass hashers/derive)))
      (-> {:result :ok}
          (response/ok)
          (assoc :session (assoc session :identity (:id user))))
      (catch Exception e
        (handle-registration-error e)))))

(register! {} {:id "foo" :pass "12345678" :pass-confirm "12345678"})
```

here is the error message:

 => #error {
 :cause "Can not issue data manipulation statements with executeQuery()."
 :via
 [{:type java.sql.SQLException
   :message "Can not issue data manipulation statements with executeQuery()."
   :at [com.mysql.jdbc.SQLError createSQLException "SQLError.java" 1055]}]

**Comment by yogthos** [comment]
What does the definition for `create-user!` look like. If you're following the book, then it should be defined in the `queries.sql` file and look something like the following:

``` sql
-- :name create-user! :! :n
-- creates a new user record
INSERT INTO users
(id, pass)
VALUES (:id, :pass)
```

Note the `:! :n` options that follow the `-- :name` declaration for the function. These are used to tell HugSQL what type of query to run. These are described in detail [here](http://www.luminusweb.net/docs/database.md#working_with_hugsql). First thing would be to check if you have those set correctly.

**Comment by g1eny0ung** [comment]
Thanks! It's true I forget add the :! :n after create-user!

And the pdf of the book I read not add the :! :n after create-user!, maybe it's a early version,I download it on the web :crying_cat_face: ,I'm sorry about I didn't buy this book.I'm a student in China and not have much money to pay for it.

Thanks :smiley:

**Comment by yogthos** [comment]
No worries, and glad it all worked out. :)
