### ISSUE TITLE
New option to pass through HugSQL options

### ISSUE THREAD

**Issue by nottmey** [luminus-framework/conman#25]
To my knowledge it is currently not possible to make use of the `options` parameter of the [encapsulated](https://github.com/luminus-framework/conman/blob/master/src/conman/core.clj#L24) `hugsql.core/def-db-fns` function ([docs](http://www.hugsql.org/#using-def-db-fns)) when using `conman.core/bind-connection` to set connection specific configurations.

I propose the use of an options map for `bind-connection`, similar showcased and helpful in #19, which is then handed to `def-db-fns`. 

In my case I need to enable `:quoting` (`:mysql`) for HugSQL functions per default. Currently this is solved by always providing the database and options map for each call of a generated HugSQL function (example in first snippet), which is far from ideal (second snippet), since connection aware functions are one key feature of conman. 

``` clojure
(db/get-user *db* {:id "foo"} {:quoting :mysql})
```

``` clojure
(db/get-user {:id "foo"})
```

**Comment by yogthos** [comment]
That sounds reasonable to me, would you by any chance be up for doing a pr? :)
