### ISSUE TITLE
Second file in conman/bind-connection throws java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by laconiccrafts** [luminus-framework/conman#28]
I have a default luminus project with the +auth and +swagger options, with two query files, queries1.sql and queries2.sql.

So I edit my conman/bind-connection in project.db.core like so:
`(conman/bind-connection *db* "sql/queries1.sql" "sql/queries2.sql")`

But when I start the server with lein run I'm getting

> Exception in thread "main" java.lang.ExceptionInInitializerError
>         at clojure.main.<clinit>(main.java:20)
> Caused by: java.lang.IllegalArgumentException: db-spec mount.core.DerefableState@2e62903f is missing a required parameter, compiling:(geo.clj:9:34)

The line the error references is where I call a function I defined in sql/queries2.sql.

It's a simple function, so I know there are no mistakes in that file: 

```
-- :name get-some-data :? :*
SELECT * FROM sometable
```

The weird thing is that if I define this function in sql/queries1.sql I don't get this error. Only functions defined AND called from the second file throw this error.

It's also weird that from the repl I can call the functions defined in the second sql file with no errors:

```
(start)
(require '[myproject.db.core :as db])
(db/some-function)
; function returns as expected

```

**Comment by yogthos** [comment]
The error you're seeing implies that the `*db*` state wasn't started when you tried to use the function. I think the issue is that the functions are being run before the database is available.

**Comment by laconiccrafts** [comment]
Yeah, it's probably something I did, but I cannot spot the error. The project with the error is in https://github.com/efraimmgon/pmmt-cljs.

I've looked at all the links in the chain and it doesn't seem like that error should be thrown, as the only change I made in the db.core was to include another file for `conman/bind-connection`.

**Comment by yogthos** [comment]
Ah, I see the problem. You have code such as [this bit](https://github.com/efraimmgon/pmmt-cljs/blob/2befb38a57f22f5672325f33cad60f1bd00f5030/src/clj/pmmt/routes/geo.clj#L15):

``` clojure
(def NATUREZAS-ID-ALL (reduce (fn [acc n]
                                (assoc acc (:id n) (:nome n)))
                              ;;test
{} (db/get-naturezas)))
```

This will end up being called at compile time, but it depends on the database resource being available. You can easily fix it by converting it to `defstate` as follows:

``` clojure
(ns pmmt.routes.geo
  (:require [ring.util.http-response :as response]
            [clojure.java.jdbc :as sql]
            [pmmt.routes.common :as c]
            [pmmt.db.core :as db :refer [*db*]]
            ;;require defstate
            [mount.core :refer [defstate]]))

...

(defstate NATUREZAS-ID-ALL
  :start (reduce (fn [acc n]
                             (assoc acc (:id n) (:nome n)))
                              ;;test
             {} (db/get-naturezas)))
```

Basically, you have to make sure that any code that calls functions in the database has to be run after the database resource becomes available.

**Comment by laconiccrafts** [comment]
This is hilarious (it's not, actually, since spent the whole day on this), because I was about to write here and tell the same thing, and that I had figured out a way around it - replacing the global vars by global functions.

Anyways, thanks for the answers and sorry for being a noob, because this error I was getting should be pretty obvious. It's my first luminus project, and I'm doing it after reading your book, which is great.

Just one last thing, is this kind of code - global vars such as that - idiomatic in Clojure, or would there be a better way of writing it? I come from a Python + Django background and I'm just now getting started on the functional programming philosophy.

**Comment by yogthos** [comment]
No worries, sometimes a second pair of eyes helps, and glad to hear you're liking the book. :)

With regards to global vars, the general rule of thumb is that you want to keep stateful code around the edges of the application. As long as core business logic is pure, you can reason about it easily and you don't need access to resources to test it. In case of something like `NATUREZAS-ID-ALL` it can make sense to keep it as a resource as it just loads some data on startup.

What I would avoid, would be passing functions that depend on the database into business logic functions. For example, say you have something like an authentication route.  This would be better:

``` clojure
(defn authenticate [user pass]
  (valid? (:pass user) pass))

(POST "/auth" [id pass]
      (let [user (db/get-user {:id id})]
        (authenticate user pass)))
```

than something like this:

``` clojure
(defn authenticate [id pass]
  (valid? (:pass (db/get-user {:id id})) pass))

(POST "/auth" [id pass]
      (authenticate id pass))
```

The idea being that in the first version we're able to test the `authenticate` function without having to have an instance of the database available. Meanwhile the route definition doesn't contain any business logic, it just fetches data from the database and returns the result to the client.

**Comment by laconiccrafts** [comment]
I see, it makes sense. 

Thanks one more time for the help, and keep on working. Your libraries are great.

**Comment by yogthos** [comment]
Thanks, that's always great to hear!
