### ISSUE TITLE
Feature request: Allow for transforming the parameter keys

### ISSUE THREAD

**Issue by ricardojmendez** [luminus-framework/conman#29]
First up, a disclaimer: maybe this is already supported and I don't quite see how. Please let me know if that's the case.

In Hughsql, we can currently create `hugsql-result-fn`s and `hugsql-command-fn`s. These allow us to transform the results from queries, say, converting keys from underscores to dashes.

I don't see that we can apply a similar transformation to the input values of a queries in a global manner.

This means you if you have a column called `first_name`, you _can_ get a result out where the key is called `:first-name`. You still have to name your parameter `:first_name` if you want the query file to be proper SQL (at least in the case of Postgres).  

While Hugsql does recognize `:first-name` on the sql script as a valid parameter, and sets it accordingly, any tool that operates over the sql file will throw up errors. For instance, IDEA will convert it to `:first - name` if you reformat the code.

It'll be great to be able to add an option to conman to convert the parameter names from keywords to snake-case during binding (or any other transformation).

I've cloned the repo and will take a stab at it during this week, but will filing it in case anyone can get to it before me.

**Comment by csummers** [comment]
@ricardojmendez I think I'm willing to put this kind of thing directly into the next version of HugSQL.  Specifically, I'm going to provide a `:transform-param-keys` and `:transform-db-keys` to handle converting incoming parameter keys (as you're asking for here) and to handle keys coming out of the database without having to override the hugsql-result-fn multimethod.

**Comment by yogthos** [comment]
Fantastic, let's leave this open as a reminder, and I can push out a new version of conman to match once it's in HugSQL.

**Comment by ricardojmendez** [comment]
Perfect, that sounds like the best place for it @csummers. Tabling this change myself then. Cheers!

**Comment by nikolap** [comment]
If using the new default with next-jdbc, you can use `:builder-fn` configurations to manage this. https://github.com/seancorfield/next-jdbc/blob/master/doc/result-set-builders.md

You would have to override the hugsql adapter, e.g.

`(hugsql/set-adapter! (next-adapter/hugsql-adapter-next-jdbc {:builder-fn my-fn-here}))`
