### ISSUE TITLE
to-jdbc-url

### ISSUE THREAD

**Issue by pupeno** [luminus-framework/conman#3]
Do you think this library should call to-jdbc-url? That could be another nice automatic think that people could take out of this, so people using conman won't even think about the fact that there are two different URL formats out there.

I would even be happy integrating to-jdbc-url into this library and killing that other one, but this is not necessary.

**Comment by yogthos** [comment]
yeah that would probably provide a better experience if the urls are handled intelligently in one place. :)

**Comment by yogthos** [comment]
Although from luminus perspective I would still need to use to-jdbc-url explicitly in migrations, since the connection there isn't managed by conman.
