### ISSUE TITLE
Documentation issue on with-transaction

### ISSUE THREAD

**Issue by ricardojmendez** [luminus-framework/conman#30]
I was about to submit a pull request for this, but given I'm not that familiar with conman, decided to open an issue instead in case I'm missing something.

There are a couple of things that look like errors [on the documentation](https://github.com/luminus-framework/conman/blob/master/src/conman/core.clj#L92-L94) for `with-transaction`:

* The example refers to `with-db-transaction` . Was this the old name?
* The same snippet seems to receive two name and connection before it goes to the k-v ones.  The example on the README only uses to the name. Is that correct?
* It refers the reader to `jdbc/db-transaction*` for more details. Shouldn't that be `jdbc/with-db-transaction`?

**Comment by yogthos** [comment]
I think that one's actually ok. The `with-transaction` macro rebinds the original connection with a transactional one within its context. Since conman generated function use the connection that was initialized in `bind-connection` by default, they end up using the transactional one.
