### ISSUE TITLE
Readme and Luminus website still reference stale clj-dbcp settings

### ISSUE THREAD

**Issue by dhruvbhatia** [luminus-framework/conman#31]
Hi DS,

It seems that the `(def pool-spec ...` sections within the Conman readme / Luminus website documentation both contain stale references to config keys which were valid for Conman when it used [clj-dbcp](https://github.com/kumarshantanu/clj-dbcp#optional-keys-for-all-jdbc-connections), but no longer valid now that it uses [@tomekw's HikariCP wrapper](https://github.com/tomekw/hikari-cp#configuration-options).

For example, the `:init-size` key doesn't mean anything in HikariCP, and hence won't do anything.

This may trip users up - it may make sense to link to @tomekw's readme so that users understand what exact parameters HikariCP takes?

**Comment by yogthos** [comment]
Thanks for the heads up, I've removed the stale keys, and added a link to the HikariCP config [here](https://github.com/luminus-framework/luminus/blob/master/resources/md/database.md). Let me know if that looks good.

**Comment by dhruvbhatia** [comment]
Thanks for the quick fix. :)
There are still a couple of stale references in the readme.md of this particular repo, but once those get updated I think all will be good!
(I would send a PR but on mobile at the moment!)

**Comment by tomekw** [comment]
Thanks guys! I've never dreamed that hikari-cp will be this popular! ;)

**Comment by yogthos** [comment]
Thanks, just updated the readme here as well. @tomekw it's a great library! :)

**Comment by dhruvbhatia** [comment]
@tomekw @yogthos thank you both!
FYI I found one more reference in README.md - have sent through a PR now (will close this issue :))
