### ISSUE TITLE
with-transaction doc

### ISSUE THREAD

**Issue by idealllee** [luminus-framework/conman#33]
super minor but should [this line](https://github.com/luminus-framework/conman/blob/master/src/conman/core.clj#L92) be updated to:
`(with-transaction [conn {:isolation level :read-only? true}]`

**Comment by yogthos** [comment]
You're absolutely right, clojure.java.jdbc API changed, and I never updated the doc string.

**Comment by vinurs** [comment]
@yogthos hello, why not update the doc string?

**Comment by yogthos** [comment]
I think it has [here](https://github.com/luminus-framework/conman/blob/3eb358c3c6184284ce1f7fa72d9a45def21eae98/src/conman/core.clj#L185), or is there a different spot I missed?

**Comment by vinurs** [comment]
because first i read the usage in readme, then using it , but didn't success;
i searched the reason for a while, and found the correct the usage;
in my mind, i believe that the readme is correct

**Comment by yogthos** [comment]
Ah I see, would you be up for doing a PR to clean up the docs based on what worked for you?

**Comment by vinurs** [comment]
@yogthos hi , i send a PR

**Comment by yogthos** [comment]
Thanks!
