### ISSUE TITLE
conman could not find the query file:sql/queries.sql

### ISSUE THREAD

**Issue by dviramontes** [luminus-framework/conman#34]
Not 💯 sure if this is an issue with conman or with my setup but im getting this error 
whenever i try to deploy a new luminus app to heroku:
```
java.lang.Exception: conman could not find the query file:sql/queries.sql, compiling:(core.clj:22:1)
remote: Exception in thread "main" java.lang.Exception: conman could not find the query file:sql/queries.sql, compiling:(core.clj:22:1)
```
Any clues as to what could be happening ?
Using `[conman "0.6.2"]` and Luminus version "2.9.11.14"
Thanks in advance!

**Comment by yogthos** [comment]
The only thing that comes to mind is to make sure that `queries.sql` is on the resource path. If it's at `sql/queries.sql`, then the path should be `resources/sql/queries.sql`. I'm not able to reproduce the problem using a fresh Luminus project.

**Comment by dviramontes** [comment]
@yogthos thanks for reply. Since this appears to be a local environment issue I'm closing for now.

**Comment by dviramontes** [comment]
actually 
@yogthos for curiosity sake, can you try this particular set of options and then deploying to heroku ?
` lein new luminus myapp +postgres +swagger +service +http-kit`
attempted this from scratch and it gave me the same error

**Comment by dviramontes** [comment]
running something like:
`lein new luminus myapp +postgres +swagger +service +http-kit && cd myapp && git init && git commit -am 'init' && heroku login ... && heroku create && git push heroku master` 
 its able to build everything correctly but towards the end it throws:
```
java.lang.Exception: conman could not find the query file:sql/queries.sql, compiling:(core.clj:22:1)
remote: Exception in thread "main" java.lang.Exception: conman could not find the query file:sql/queries.sql, compiling:(core.clj:22:1)
```
could it be that the particular set of profile flags contradict each other in some way ?
For the moment i got around it by removing the `+postgres` profile flag

**Comment by yogthos** [comment]
Everything looks right to me there. Could you try making a local uberjar and see if it works locally by running `lein uberjar` and then `java -Ddatabase-url="jdbc:postgresql://localhost:5432/dbname?user=user&password=pass" -jar target/myapp.jar`.

Another thing to check is that the project is being generated with the latest template. The current version is `2.9.11.14`, so you can check `README.md` for the generated project to see whether it matches. Also check the version of the conman dependency.

**Comment by dviramontes** [comment]
Check the uberjar. It worked fine locally. Im also using latest template. Closing for now, it appears to be a local environment issue.

**Comment by stefanroex** [comment]
@dviramontes I've just run into the same issue. After some debugging I found out that my global `.gitignore` ignored all sql files 😄 (d'oh!) . Adding the sql files to git fixed the problem for me.

**Comment by yogthos** [comment]
that would do it :)

**Comment by dviramontes** [comment]
@stefanroex 🙏
