### ISSUE TITLE
connecting to oracle DB

### ISSUE THREAD

**Issue by hadielmougy** [luminus-framework/conman#35]
I'm struggling connecting luminus to oracle db using the following URL
jdbc:oracle:thin:username/password@10.29.10.214:1521:orcl

I'm getting -- Error creating DB connection for jdbc:oracle:thin....

**Comment by yogthos** [comment]
The URL I use for oracle is `jdbc:oracle:thin:user/pass@//host:1521/schema`

**Comment by yogthos** [comment]
Can we close this one, or are you still having problems connecting? It doesn't appear to be a conman specific issue from what I can tell.

**Comment by yogthos** [comment]
I'm going to close the issue for now, since I'm not able to reproduce the error. If you discover there's something conman specific happening we can reopen it.
