### ISSUE TITLE
Dynamic binding

### ISSUE THREAD

**Issue by fdabrao** [luminus-framework/conman#36]
Hello,

Is there any way to do something like this?
`(conman/bind-connection *db* (str "sql/" database ".sql"))` ?
I tried but it don´t compile by lein uberjar.

Regards

**Comment by yogthos** [comment]
Unfortunately it's not possible at the moment since `bind-connection` is a macro, and it expects a string literals for query file names.

**Comment by fdabrao** [comment]
So how can I use this bind switching sql file for database id from string:
example: 
"oracle" -> load sql/oracle.sql
"sqlserver" -> load sql/sqlserver.sql ?

**Comment by yogthos** [comment]
the easiest would be to do something like

```clojure
(case db-type
  "oracle"    (conman/bind-connection *db* "sql/oracle.sql")
  "sqlserver" (conman/bind-connection *db* "sql/sqlserver.sql"))
```
