### ISSUE TITLE
bind-connection generates anonymous functions

### ISSUE THREAD

**Issue by technomancy** [luminus-framework/conman#41]
When a function generated by `bind-connection` throws an exception, the stack frame looks something like `myapp.queries/eval29331/fn--29332`. The name for this function is known at function definition time, but it's not included in the function.

I believe it would be more debuggable to construct a `fn` that has an internal name in order to improve stack traces. However, I think the way things are structured right now this would require using `eval`--something like this:

```clj
       (doseq [[id# {fn# :fn {doc# :doc} :meta}] fns#]
         (intern *ns* (with-meta (symbol (name id#)) {:doc doc#})
                 (eval (list 'fn (symbol name #id)
                             '([] (fn# ~conn {}))
                             '([params#] (fn# ~conn params#))
                             '([conn# params#] (fn# conn# params#))
                             '([conn# params# opts# & command-opts#]
                              (apply fn# conn# params# opts# command-opts#))))))
```

Thoughts?

**Comment by yogthos** [comment]
I think the improved errors would definitely be a plus. I'm ok with the `eval` approach as I can't really think of anything better.

**Comment by technomancy** [comment]
Another suggestion I received would be to wrap it in a `try/catch` which can re-throw with an error message that contains the function name.

**Comment by yogthos** [comment]
Ah yeah that's probably cleaner than doing eval, and would allow for a more meaningful error message as well. Would you be up for doing a PR for this?

**Comment by technomancy** [comment]
Sure thing, just wanted to check first that you were on board with the idea.

**Comment by yogthos** [comment]
Absolutely, good error messages are important.
