### ISSUE TITLE
Error when AOT compiling

### ISSUE THREAD

**Issue by kanwei** [luminus-framework/conman#43]
I will sometimes get this error on load (AOT compiled). It only happens around 20% of the time-ish, and it seems to be AOT related since restarting the process consistently has the error.

```No such var: adp/hugsql-adapter-clojure-java-jdbc```

Related to https://github.com/layerware/hugsql/issues/46

**Comment by yogthos** [comment]
Looks like hugsql addressed the issue, so should be fixed transitively here as well.
