### ISSUE TITLE
Tools for testing

### ISSUE THREAD

**Issue by pupeno** [luminus-framework/conman#5]
I think it would be nice of conman offered some tools for testing. In luminus-template we already have the fixture that connects to the database, runs migrations. I also ended up writing this fixture:

``` clojure
(use-fixtures
  :each
  (fn [test-function]
    (conman/with-transaction
      [t-conn db/conn]
      (jdbc/db-set-rollback-only! t-conn)
      (test-function))))
```

I ended up putting them both in a function:

``` clojure
(defn set-up-database-test []
  (use-fixtures
   :once
   (fn [f]
     (db/connect!)
     (migrations/migrate ["migrate"])
     (f)))

  (use-fixtures
    :each
    (fn [test-function]
      (conman/with-transaction
        [t-conn db/conn]
        (jdbc/db-set-rollback-only! t-conn)
        (test-function)))))
```

It would require some work to find the right set of interfaces here, to make sure we can operate with any or many connections. This also ties with the migration library, which I don't think it's a bad thing as we use yesql already.

**Comment by yogthos** [comment]
I would prefer to keep the library focused myself. I'm not a big fan of omnibus libraries to be honest. I think testing and migrations are different concerns from connection management. I think it would be better to create a separate library that uses conman to provide a test harness instead.
