### ISSUE TITLE
Connect To oracle database

### ISSUE THREAD

**Issue by mondaldebanjan** [luminus-framework/conman#57]
How to connect to oracle db?
What will be the url how to change the library?

**Comment by yogthos** [comment]
You just have to give it an [Oracle JDBC URL](https://docs.oracle.com/cd/E11882_01/appdev.112/e13995/oracle/jdbc/OracleDriver.html), e.g:

```clojure
(conman/connect! {:jdbc-url "jdbc:oracle:thin:@myhost:1521:orcl"})
```

**Comment by mondaldebanjan** [comment]
i have made the template according to +mysql 
and changed the jdbc url 
but when i run migrate
No suitable driver found for jdbc:oracle:thin.... it shows

**Comment by mondaldebanjan** [comment]
where else i have to change ? and where i can put my driver?
Please help me here

**Comment by yogthos** [comment]
You have to add the Oracle driver dependency in project.clj, unfortunately Oracle doesn't publish their drivers on public Maven repositories.

So, you'd have to download the driver from the Oracle site, and do a local install for it.

**Comment by mondaldebanjan** [comment]
ok Thank you

**Comment by mondaldebanjan** [comment]
now having an error while migrating:
at clojure.main.main(main.java:37)
Caused by: java.sql.BatchUpdateException: error occurred during batching: ORA-00902: invalid datatype

        at oracle.jdbc.driver.OracleStatement.executeBatch(OracleStatement.java:4615)
        at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:230)

**Comment by yogthos** [comment]
That sounds like you have a type mismatch between the table column and the type of the data you're trying to set there. It does appear that you're able to connect to the db via conman though.

**Comment by mondaldebanjan** [comment]
yes it is now connected :)

**Comment by yogthos** [comment]
cool, I think we can close this one as the other problems don't appear to be conman related :)

**Comment by mondaldebanjan** [comment]
any update on this one ? 
https://github.com/yogthos/migratus/issues/43
