### ISSUE TITLE
From the user namespace how do I reload queries from the REPL?

### ISSUE THREAD

**Issue by mudgen** [luminus-framework/conman#58]
I am using the user namespace in my luminous application to restart parts of my application from the REPL. But this does not work with changing database queries in the queries.sql file. Here is what I have tried that does not work:

```
(defn restart-db []
  (mount/stop #'mokens.db.core/*db*)
  (mount/start #'mokens.db.core/*db*)
  (conman/bind-connection #'mokens.db.core/*db* "sql/queries.sql"))
```

How can I make this work so my queries are reloaded when I call user/restart-db from the REPL?

**Comment by mudgen** [comment]
Doing this works but doesn't seem like a good way:

```
(defn restart-db []
  (mount/stop #'mokens.db.core/*db*)
  (mount/start #'mokens.db.core/*db*)
  (binding [*ns* 'mokens.db.core]
    (conman/bind-connection mokens.db.core/*db* "sql/queries.sql")))
```

**Comment by yogthos** [comment]
That's the best way to handle that at the moment. Since the queries need to be reloaded in the db namespace, that's pretty much the only option.

**Comment by mudgen** [comment]
Okay, thanks!
