### ISSUE TITLE
Weird behaviour when trying to run a test

### ISSUE THREAD

**Issue by aarkerio** [luminus-framework/conman#60]
On my luminus app I have one test file, when I try to run it with the command:  

`  $ lein with-profile test test`

I'm getting

`Caused by: java.lang.IllegalArgumentException: db-spec mount.core.DerefableState@5cb2f9e7 is missing a required parameter `

Digging a little I see that the problem is the app is unable to connect with the database.

The weird thing is that if I run  

`  $ lein with-profile test run`

I mean, run the whole app in the "test" profile, all works perfectly and I can insert/update/delete in the database. I'm guessing that the function:

`(start-app args)`

in the core.clj file, does something that "repl" and "test" don't do, but since I'm kind of newbie in the clojure world, I don't know what part could be.  Maybe do I need to add a function to run  the tests in luminus?

This are my project and core files:
 
https://github.com/aarkerio/ZentaurLMS/blob/development/project.clj
https://github.com/aarkerio/ZentaurLMS/blob/development/src/clj/zentaur/core.clj

**Comment by yogthos** [comment]
I think you might be missing the configuration for tests. Luminus sets up a project with separate configurations for development and testing. This is managed by the `:jvm-opts` key in the profiles. If you at the test profile in `project.clj`, it has the following line there: `:jvm-opts ["-Dconf=test-config.edn"]`. So, you should add the database URL for the test database there, and you should be able to run the tests either using `lein test` or with `lein test-refresh` which will watch the project for changes and run tests as needed.

**Comment by yogthos** [comment]
Actually, just checked your `project.clj`, and it looks like it's based off the older version of the template that uses `lein-cprop` plugin to generate the `.lein-env` config file. My recommendation would be to get rid of `lein-cprop` along with the `:jvm-opts ["-server" "-Dconf=.lein-env"]` at the top level, and create separate JVM opts for dev and testing profiles keeping the configs in files like `dev-config.edn` and `test-config.edn`.
