### ISSUE TITLE
SQL query debug

### ISSUE THREAD

**Issue by alexander982** [luminus-framework/conman#61]
I have a complex query which works fine in h2 web console and when I use clojure.java.jdbc api and returns meaningful results . When I try to use conman it returns nil values.
```
--:name get-metals-by-id :? :1
with recursive sostav (pref, num, name, qnt, gold, silver, pl, pal, id) as (
SELECT u2.prefix, u2.num, u2.name, c.qnt,
u2.gold, u2.silver, u2.pl, u2.pal, u2.id
FROM (unit u inner join contain c on u.id = c.cont_id)
inner join unit u2 on u2.id  = c.unit_id
where u.id = :id
union all
select u.prefix, u.num, u.name, c.qnt, u.gold, u.silver, u.pl, u.pal, u.id
from ( sostav s inner join contain c on s.id = c.cont_id)
inner join unit u on c.unit_id = u.id)
select sum(cast(gold as double)*cast(qnt as int)) as gold,
sum(cast(silver as double)*cast(qnt as int)) as silver,
sum(cast(pl as double)*cast(qnt as int)) as pl,
sum(cast(pal as double)*cast(qnt as int)) as pal
from sostav;
```
As i see there is no access to HugSQL sqlvec functions. Is there a way to solve my problem?

**Comment by yogthos** [comment]
Conman is a thin wrapper around HugSQL functions, so you should be able to mix HugSQL functions with the ones generated by conman.

**Comment by alexander982** [comment]
Thanks for the advice. I think I already found the root of the problem. The point is the limitations of recursive queries in the H2 database and SQL parameter binding by HugSQL.
