### ISSUE TITLE
Options are not evaluated in bind-connection(-deref)

### ISSUE THREAD

**Issue by svdm** [luminus-framework/conman#62]
Since 0.8.2, when passing an option map to `bind-connection` or `bind-connection-deref`, that map is never evaluated. Instead the contents are passed to the bound Hugsql functions as literals.

This is a problem when doing something like:

    (bind-connection-deref conn {:adapter (hugsql-adapter-clojure-java-jdbc)} "queries.sql")

Hugsql then tries to use that literal list `'(hugsql-adapter-clojure-java-jdbc)` as adapter instead of the value of the expression, resulting in obscure exceptions such as `java.lang.IllegalArgumentException: No implementation of method: :on-exception of protocol: #'hugsql.adapter/HugsqlAdapter found for class: clojure.lang.PersistentList`.

This bug was introduced in the refactor of 8702e2bb1ec4. Previously the options were [split out and then unquoted](https://github.com/luminus-framework/conman/blob/9e7d3c72958bc4126f660f8b564c9b0e96e75e2d/src/conman/core.clj#L80). Now the `filenames` list is emitted untouched and then quoted so the options remain unevaluated, while `load-queries` expects evaluated args.

From what I can tell the easiest fix is to splicing-unquote `filenames` (ie. `(conman.core/load-queries ~@filenames)`) and change `load-queries` to take `& args`. The logic in `load-queries` to split out the options from the filenames should then just work.

**Comment by yogthos** [comment]
Yeah, that sounds reasonable. Would you be ok doing a PR for this since it's a small change and you can test it in your use case?
