### ISSUE TITLE
Clojure docker build fail for lein compile

### ISSUE THREAD

**Issue by priyankaMedidata** [luminus-framework/conman#64]
The `lein compile` for clojure fails during deploy which was working until yesterday. 
Below is stack trace
`23:33:19 - java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to java.base/java.lang.String
23:33:19 - at cemerick.pomegranate.aether$authentication.invokeStatic (aether.clj:173)
23:33:19 - cemerick.pomegranate.aether$authentication.invoke (aether.clj:173)
23:33:19 - cemerick.pomegranate.aether$set_authentication.invokeStatic (aether.clj:184)
23:33:19 - cemerick.pomegranate.aether$set_authentication.invoke (aether.clj:181)
23:33:19 - cemerick.pomegranate.aether$make_repository.invokeStatic (aether.clj:207)
23:33:19 - cemerick.pomegranate.aether$make_repository.invoke (aether.clj:200)
23:33:19 - cemerick.pomegranate.aether$resolve_dependencies_STAR_$fn__219.invoke (aether.clj:798)
23:33:19 - clojure.core$map$fn__4785.invoke (core.clj:2644)
23:33:19 - clojure.lang.LazySeq.sval (LazySeq.java:40)
23:33:19 - clojure.lang.LazySeq.seq (LazySeq.java:49)
23:33:19 - clojure.lang.ChunkedCons.chunkedNext (ChunkedCons.java:59)
23:33:19 - clojure.lang.ChunkedCons.next (ChunkedCons.java:43)
23:33:19 - clojure.lang.PersistentVector.create (PersistentVector.java:73)
23:33:19 - clojure.lang.LazilyPersistentVector.create (LazilyPersistentVector.java:44)
23:33:19 - clojure.core$vec.invokeStatic (core.clj:377)
23:33:19 - clojure.core$vec.invoke (core.clj:367)
23:33:19 - cemerick.pomegranate.aether$resolve_dependencies_STAR_.invokeStatic (aether.clj:798)
23:33:19 - cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke (aether.clj:707)
23:33:19 - clojure.lang.RestFn.applyTo (RestFn.java:137)
23:33:19 - clojure.core$apply.invokeStatic (core.clj:646)
23:33:19 - clojure.core$apply.invoke (core.clj:641)
23:33:19 - cemerick.pomegranate.aether$resolve_dependencies.invokeStatic (aether.clj:815)
23:33:19 - cemerick.pomegranate.aether$resolve_dependencies.doInvoke (aether.clj:809)`

**Comment by yogthos** [comment]
Hi, it looks like you're getting a type mismatch somewhere. However, the trace appears to be coming from [this](https://github.com/cemerick/pomegranate) library and does not seem to be related to conman.
