### ISSUE TITLE
would it support sharding-jdbc

### ISSUE THREAD

**Issue by vinurs** [luminus-framework/conman#65]
if we face thousands of millions of data, we need to split the databases and tables, there is [sharding-jdbc](https://github.com/apache/incubator-shardingsphere) for java, then it is need to port to clojure ?

**Comment by yogthos** [comment]
It's probably easiest to just call the library via interop, looks like you just add the dependency and create a data source according to the docs [here](https://shardingsphere.apache.org/document/current/en/quick-start/sharding-jdbc-quick-start/). I don't think you'd need to use conman with it though.

**Comment by vinurs** [comment]
then if i want to use it with hugsql，then i need to
write a adapter？

**Comment by yogthos** [comment]
Hugsql generates query functions that accept a db-spec, a connection, a connection pool, or a transaction object explicitly as their first argument. So, you would create a connection using sharding-jdbc and pass it to the functions.
