### ISSUE TITLE
disconnect! does nothing to return value of connect!

### ISSUE THREAD

**Issue by polymeris** [luminus-framework/conman#70]
Is this how connect!/disconnect! is supposed to be used?
```
(let [conn (connect! {:jdbc-url "..."})]
  ; do stuff with conn
  ; ...
  ; then release conn:
  (disconnect! conn))
```
If so, and given that conn does not have a `:datasource` key, I think `disconnect!` never does anything: https://github.com/luminus-framework/conman/blob/master/src/conman/core.clj#L162

EDIT:
Noticed this because I was getting `PSQLException`s with "FATAL: sorry, too many clients already" when I reloaded the system.

**Comment by yogthos** [comment]
Conman creates a [HikariCP connection pool](https://github.com/brettwooldridge/HikariCP) datasource in [connect!](https://github.com/luminus-framework/conman/blob/9684b1b20770e63e2c55566f0672b22bae257487/src/conman/core.clj#L156) by calling `hikari-cp.core/make-datasource`, that returns a map with `{:datasource <pooled datasource>}`. Hence, `disconnect!` can expect the `:datasource` key regardless of the parameters `connect!` was called with.

**Comment by polymeris** [comment]
Maybe I am missing something, but `hikari-cp.core/make-datasource` seems to return a plain `HikariDataSource`:

https://github.com/tomekw/hikari-cp/blob/master/src/hikari_cp/core.clj#L264

**Comment by polymeris** [comment]
I think this change might have broken it: https://github.com/luminus-framework/conman/commit/f1847b2aff11052a3c4cd934f97b8bf2cc8bffb2#diff-ba7b8a6eee2285cb25755ff24fac5747R153

**Comment by yogthos** [comment]
Hmm, hikari-cp docs show that it should return a map [here](https://github.com/tomekw/hikari-cp#postgresql-example), but could be out of sync with what's happening. Let me try this out.

**Comment by yogthos** [comment]
So, looks like it does return the raw data source from hikari-cp, just pushed out 0.8.7 with the fix.

**Comment by polymeris** [comment]
That was fast, thank you!

**Comment by yogthos** [comment]
No prob, and sorry for the confusion earlier. I should've looked at the actual code instead of the docs. :)
