### ISSUE TITLE
Request for support for HugSQL tuple list queries 

### ISSUE THREAD

**Issue by ILoveHubGit** [luminus-framework/conman#73]
I'm trying to use the batch form of an insert statement;
`INSERT INTO Table (column1, column2) 
VALUES ("value1", 1),("value2",2)`
This because I want to be able to insert thousands of records per second.

According to the [HugSQL documentation ](https://www.hugsql.org/#param-tuple-list) this is possible by using `:t*:params` in the query definition in the sql file. However for this to work the function 'map-of-sqlvec-fns' should be called when reading the sql query definitions. After this it is possible to call a database function with the suffix -sqlvec if you want to use the batch version.

I think it is easy to add this to the conman bind-connection function by changing this line:
`(hugsql/map-of-db-fns file options)`
to
`(merge (hugsql/map-of-db-fns file options) (hugsql/map-of-sqlvec-fns file options)`

It is then up to the user which function to call, the one with or without the suffix -sqlvec.

I would very much appreciate if you can add this functionality.

**Comment by yogthos** [comment]
I'd be open for adding the feature, but won't have time to look in the near future. If you'd be up for doing a PR I'd be happy to assist with that.

**Comment by ILoveHubGit** [comment]
I was a bit to optimistic when I created this request for support. Although the merge I describe above does the trick to make also the queries available with a suffix -sqlvec, these functions can be used out of the box after this.
I tried a while to make the correct changes but because I had some pressure in the project I needed this for I didn't finish it.

To solve my problem I relied directly on `next.jdbc` the library behind `hugsql` you're using. Maybe the solution I found can help you solve it in `conman`. But I think `hugsql` has to make code changes as well, unless you want to use `next.jdbc` directly.

Let me describe it in en example. Let's say I want to write multiple records using one INSERT statement to a database. In most databases this is possible with an SQL statement like this:
```
INSERT INTO table_name (ietm1, item2, item3)
VALUES
    (value1a, value2a, value3a),
    (value1b, value2b, value3b),
    ...
    (value1n, value2n, value3n);
```
I added `[seancorfield/next.jdbc "1.1.613"]` to my project.clj. Then added `[next.jdbc :as jdbc]` and `[next.jdbc.sql :as sql]` to myproject.db.core.clj

I created a function like this:
```
(defn sqlvec-items!
  [items]
  (let [ds (jdbc/get-datasource *db*)]
    (sql/insert-multi! ds :items
                          [:item1 :item2 :item3]
                          items)))
```
`*db*` is the default database connection as created when starting a new project with `lein`

`items` is a vector of vectors `[[value1a value2a value3a] [value1b value2b value3b] [value1c value2c value3c]]`

Maybe this is of any help to you

**Comment by yogthos** [comment]
I think you're right that this would probably make sense as an extension in hugsql, but using underlying jdbc.next is a good workaround. I just pushed out `0.9.1` with the updated jdbc.next dependency so you don't have to include it explicitly.

**Comment by sunng87** [comment]
This should be supported by introduction of `next.jdbc` as default backend.
