### ISSUE TITLE
Getting the meta of the query, not the queries

### ISSUE THREAD

**Issue by pupeno** [luminus-framework/conman#9]
In this line:

``` clojure
(with-meta (:name (meta yesql-query#)) (meta yesql-queries#))
```

https://github.com/luminus-framework/conman/blob/master/src/conman/core.clj#L22

I think meta should refer to `yesql-query`, not `yesql-queries`. Am I wrong?

**Comment by yogthos** [comment]
fixed to use `(:name (meta yesql-query#))` that contains the query name for interning
